### ISSUE TITLE
Changing Search Navigation Icon Not Working

### ISSUE THREAD

**Issue by patrickoramah** [lapism/MaterialSearchView#112]

**Comment by lapism** [comment]
And I need more info. Which version are you using?  Update to last 3.3.2 and use MENU ITEM OR TOOLBAR ICON.

**Comment by patrickoramah** [comment]
I am using 3.3.2 i need to change the menu/navigation icon to an up button icon but when i use app:search_navigation_icon or searchView.setNavigationIcon the up button/navigation  icon dosen't change

**Comment by ivamluz** [comment]
@patrickoramah, I believe you should be able to achieve what you want by calling searchView.setVersion(SearchView.VERSION_TOOLBAR_ICON);

**Comment by patrickoramah** [comment]
Thank you very Much. IT WORKED!!!

**Comment by ivamluz** [comment]
You are welcome :)

**Comment by lapism** [comment]
I know that it is a little bit confusing but I don't want to change anything important while I add new things because a lot of people would had to change their code.

**Comment by anargu** [comment]
Just an observation.

I was stuck in how to change the voice icon and/or menu icon. I couldn't figure out why this line

        search_bar.setMicIcon(R.drawable.ic_search)

weren't working as expected. Then I figured out why. I put the `setIcon(...` before the `setOnClickListener(...`. 

and what setOnClickListener does is this: 

```
public void setOnMicClickListener(Search.OnMicClickListener listener) {
        mOnMicClickListener = listener;
        if (mOnMicClickListener != null) {
            mImageViewMic.setVisibility(View.VISIBLE);
            if (mTheme == Search.Theme.GOOGLE) {
                mImageViewMic.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.search_ic_mic_color_24dp));
            } else {
                mImageViewMic.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.search_ic_mic_black_24dp));
            }
        } else {
            mImageViewMic.setVisibility(View.GONE);
        }
    }
```

It's setting again the icon for Voice Icon. and probably this will do the same for menu Icon. Maybe this could be an issue. But at the end I could ended up with a solution: put `setOnClickListener` before `setIcon`
